### ISSUE TITLE
What signal is for lock state of the car

### ISSUE THREAD

**Issue by LexNastin** [joshwardell/model3dbc#4]
I've been looking all over and can't find the signal for whether the car is locked or not... I specifically recall seeing a lock state for the separate doors but I might be mistaken... could someone help?

Thx in advance 😉!

**Comment by LexNastin** [comment]
And if there is no such signal atm, would there be any other to check if the car is locked or not? (Without the TeslaAPI btw)

The best I found so far was vehicleUnlockRequest but not even vehicleLockRequest :/

**Comment by k-korn** [comment]
It would be better to ask such questions at the forum: https://teslaownersonline.com/threads/diagnostic-port-and-data-access.7502/

As for the issue - door lock status is definitely there, as well as driver/passenger presence (ID3A1).

**Comment by LexNastin** [comment]
![image](https://user-images.githubusercontent.com/32967396/89026946-7fd0e700-d321-11ea-92b8-fdf0faa48bd8.png)
would this be it?

**Comment by LexNastin** [comment]
Thx btw!

**Comment by LexNastin** [comment]
> ![image](https://user-images.githubusercontent.com/32967396/89026946-7fd0e700-d321-11ea-92b8-fdf0faa48bd8.png)
> would this be it?

Cuz i'm not home to test it and would want to finish my arduino application by that time

**Comment by joshwardell** [comment]
I haven't seen a door lock/unlock singnal. But this is not an issue with the DBC.
